### PR TITLE
Vendoring: use go dep

### PR DESCRIPTION
**Pull request by adrianosela**
```
rm -rf vendor
dep init
dep ensure -update
```

### CODE REVIEW

**Comment by ajvb** [comment]
I'm going to suggest that we do not use go dep, but instead wait until Go Modules are officially supported and switch to that.

**Comment by adrianosela** [comment]
@ajvb not a bad idea given that "Go 1.13 is scheduled for August 2019" - src: https://blog.golang.org/modules2019

thoughts @ameihm0912 ?

**Comment by ameihm0912** [comment]
> @ajvb not a bad idea given that "Go 1.13 is scheduled for August 2019" - src: https://blog.golang.org/modules2019
> 
> thoughts @ameihm0912 ?

yeah I think that makes sense

**Comment by adrianosela** [comment]
closing PR and opened issue: https://github.com/mozilla-services/iprepd/issues/32

**Pull request closed without merging**
